### ISSUE TITLE
Throw Error when collectGitInfo fails

### ISSUE THREAD

**Issue by ryfloyd** [mattn/goveralls#105]
I spent far too long to understand why my reports to Coveralls.io was not showing any branch info, commit message, etc.  My app is built with Docker, and it was excluding `.git` folder in my `.dockerignore` file.  This resulted with missing formdata POST to coveralls.io. 

Easily fixed by just including `.git` folder to my Docker container.

**Comment by mattn** [comment]
Do you expect that update README.md?

**Comment by ryfloyd** [comment]
Perhaps a warning log if the directory is missing the `.git`?

**Comment by gdm85** [comment]
The python tool has the possibility to pass the `git` information via environment variables; that is also possible for the codecov official tool and in general it is a good practice to **not** bloat the Docker image with the `.git` directory.

@mattn I would like to submit a PR to add support for `git` information via environment variables; I would use these for reference: https://github.com/coveralls-clients/coveralls-python/blob/a5de3ba/coveralls/git.py#L101

After that I can also add a CLI flag `-require-git=false` which - when set to true - makes the tool fail; this way we can prevent the existing behaviour (an error is printed) but allow more strict behaviours for troubleshooting and integrations.

What do you think?

**Comment by gdm85** [comment]
Implemented in #188
