### ISSUE TITLE
Adding TeamCity service

### ISSUE THREAD

**Issue by pawanrawal** [mattn/goveralls#106]
Are there any plans to add https://www.jetbrains.com/teamcity/ to the list of supported services? Or is there any workaround to make it work on TeamCity?

**Comment by rogchap** [comment]
Hey @pawanrawal We have a similar request, but for Bulkite.

I had a look at the code and it's pretty easy to get it to work with another CI Platform. the `-service` flag is only text that gets passed through to the API and then you just need to override a few Environment Variables to get the PR number, Branch etc.

This is a how we did it for Buildkite, I'm sure Team City would be similar:

```bash
# goveralls only support travis CI and Circle CI so we export ENVs for Buildkite instead.
export TRAVIS_JOB_ID=$BUILDKITE_BUILD_NUMBER
export CIRCLE_PR_NUMBER=$BUILDKITE_PULL_REQUEST
export GIT_BRANCH=$BUILDKITE_BRANCH

$GO test -v -covermode=count -coverprofile=coverage.out
$GOPATH/bin/goveralls -coverprofile=coverage.out -service=Buildkite -repotoken $COVERALLS_TOKEN
```

**Comment by mattn** [comment]
I don't use termcity. So if you got succeeded to post, please send me PR to update README. :)
