### ISSUE TITLE
crash when checking multiple 'main' packages

### ISSUE THREAD

**Issue by BenLubar** [mattn/goveralls#11]
a/dummy_test.go

    package main
    
    import "testing"
    
    func TestDummy(t *testing.T) {
    }

a/main.go

    package main
    
    import (
            "fmt"
    )
    
    type foo struct {
            bar string
    }
    
    func main() {
            var f foo
            f.bar = "a"
            fmt.Println(f.bar)
    }

b/dummy_test.go

    package main
    
    import "testing"
    
    func TestDummy(t *testing.T) {
    }

b/main.go

    package main
    
    import "fmt"
    
    func main() {
            fmt.Println("b")
    }

command and output:

    $ goveralls -package ./... INVALID_KEY
    ok      a  0.002s
    ok      b  0.003s
    15:58:29 goveralls.go:287: How did we get here??
    panic: How did we get here??
    
    goroutine 1 [running]:
    log.Panic(0x7fed418b4aa8, 0x1, 0x1)
            /opt/golang/src/pkg/log/log.go:307 +0xb5
    main.main()
            /home/ben/go/src/github.com/mattn/goveralls/goveralls.go:287 +0x2983
    
    goroutine 6 [finalizer wait]:
    runtime.park(0x410de0, 0x9b9a08, 0x9b7829)
            /opt/golang/src/pkg/runtime/proc.c:1334 +0x66
    runfinq()
            /opt/golang/src/pkg/runtime/mgc0.c:2271 +0x84
    runtime.goexit()
            /opt/golang/src/pkg/runtime/proc.c:1386

**Comment by mattn** [comment]
Should be alreadly fixed in latest.
