### ISSUE TITLE
travis exits with 1 - no packages depend on ..

### ISSUE THREAD

**Issue by hhrutter** [mattn/goveralls#112]
Hi!

I just started getting travis failures that look like so:

```
$ $HOME/gopath/bin/goveralls -service=travis-ci
signal: killed: warning: no packages being tested depend on github.com/hhrutter/pdfcpu/cmd/pdfcpu
warning: no packages being tested depend on github.com/hhrutter/pdfcpu/create
The command "$HOME/gopath/bin/goveralls -service=travis-ci" exited with 1.
```

My travis build used to work and my local go test ./... also works.
My local environment is: go version go1.9.3 darwin/amd64

What am I missing here?

**Comment by mattn** [comment]
goveralls doesn't support test for multiple packages.

**Comment by mattn** [comment]
please show me your .travis.yml

**Comment by hhrutter** [comment]
Fixed! Too much logging output then testing takes too much time
But this is in no way reflected in the error message..
Anyway - I am happy.
