### ISSUE TITLE
Can't get to work on drone.io

### ISSUE THREAD

**Issue by rayjlinden** [mattn/goveralls#124]
goveralls -coverprofile=cover.profile -service=drone.io -repotoken $$COVERALLS_TOKEN
Bad response status from coveralls: 422
{"message":"Couldn't find a repository matching this job.","error":true}

**Comment by mattn** [comment]
Sorry, I don't use drone.io at the least.

**Comment by gdm85** [comment]
@rayjlinden did you solve the issue?

**Comment by rayjlinden** [comment]
Nope.  Ended up building our own alternative to goveralls...

**Comment by gdm85** [comment]
Alright, thanks!

Closing until issue can be reproduced.
