### ISSUE TITLE
Invalid commit message

### ISSUE THREAD

**Issue by diegobernardes** [mattn/goveralls#134]
This is the first time this kind of weird error occurs to me, so I think that may be something related to Azure Pipelines, as is also the first time I've been using it. The commit messages are very weird at Coveralls:

https://coveralls.io/github/pipehub/pipehub
![image](https://user-images.githubusercontent.com/14483/56598095-b7fc5c80-65eb-11e9-97e6-d08c78e7a879.png)

Any idea?

**Comment by mattn** [comment]
As far as I remember, goveralls does not send commit message to coverall.

**Comment by shogo82148** [comment]
It looks that the commit message is created by GitHub, and it's not goveralls' issue.
please go to Azure Pipelines forum or help desk.
