### ISSUE TITLE
Not Supported by Github Actions

### ISSUE THREAD

**Issue by eduncan911** [mattn/goveralls#140]
There is an error here when trying to use with default GitHub actions.

https://github.com/mattn/goveralls/blob/master/gocover.go#L25

The issue is that GitHub Actions checks the code out into a non-GOPATH location.

I have to force a checkout of the code into a GOPATH location, and then coveralls runs.  Notice the commands to `go get` my own repo.  This is different than the default Golang runners they have, which errors (I had to bypass it).

https://github.com/eduncan911/github-actions/blob/master/.github/workflows/go.yml

**Comment by nhooyr** [comment]
See #141 

I did not have this issue. I don't see why overalls would need to support modules as it uses `go test` which should. Maybe you're on an old version of Go on CI?

**Comment by eduncan911** [comment]
Go 1.11 and Go 1.12, pretty recent.

So in that PR, you're checking out Go code into a path outside of the GOPATH?

Here's the full CI run, where it's checking out to a non GOPATH, and running goveralls.

https://github.com/eduncan911/github-actions/commit/66d6ccde96546ce02e5ad494a23bd74e1190a1a0/checks?check_suite_id=260823215

The actual error is:

```
Test1s
##[error]Process completed with exit code 1.
Run go test -covermode count -coverprofile cover.out
PASS
coverage: 57.1% of statements
ok  	_/home/runner/work/github-actions/github-actions	0.002s
mode: count
/home/runner/work/github-actions/github-actions/main.go:13.48,14.21 1 2
/home/runner/work/github-actions/github-actions/main.go:19.2,19.14 1 1
/home/runner/work/github-actions/github-actions/main.go:14.21,16.3 1 0
/home/runner/work/github-actions/github-actions/main.go:16.8,16.28 1 2
/home/runner/work/github-actions/github-actions/main.go:16.28,18.3 1 1
/home/runner/work/github-actions/github-actions/main.go:22.13,26.2 2 0
06:41:29 gocover.go:90: Can't find can't find "main.go": import "/home/runner/work/github-actions/github-actions/": cannot import absolute path
##[error]Process completed with exit code 1.
```

**Comment by nhooyr** [comment]
> So in that PR, you're checking out Go code into a path outside of the GOPATH?

Yes I am.

I'm not sure what's going on with your run. Feel free to try to use my code verbatim.

**Comment by eduncan911** [comment]
Yeah, it's odd.

I don't have the `cover.out` handy, but it basically lists full file paths to like /home/runner/work/repo/main.go

Once I moved the go code to checkout into /home/runner/go/sex/GitHub.com/repo/main.go, it works!

I even checked out an older tag here, as used a few years ago - same issue.  

I'll close this for now since you're unable to repo.

**Comment by dtitov** [comment]
I'm actually having the same issue: https://github.com/uio-bmi/lega-uploader/commit/ab08d7acaa224bb13e3aadb906ce698b3e4a3c08/checks?check_suite_id=399511082

Did you figure out anything about this?

**Comment by eduncan911** [comment]
I just had to bypass it, as I linked to above:

https://github.com/eduncan911/github-actions/blob/master/.github/workflows/go.yml

**Comment by shogo82148** [comment]
You need to set the `$GOPATH` environment value or the `go.mod` file.
