### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by mattn** [mattn/goveralls#149]
I already don't use goveralls. So it is difficult to maintain this. Anyone want to maintain this?

**Comment by shogo82148** [comment]
🙋‍♂ 

I'm use goveralls via https://github.com/marketplace/actions/actions-goveralls

**Comment by rcmachado** [comment]
Maybe someone from @lemurheavy can help (since it seems they are responsible for the Coveralls service)?

**Comment by nbaztec** [comment]
I can volunteer, already maintaining the Kotlin version for Coveralls and Golang is my primary language :)

**Comment by gdm85** [comment]
@mattn I volunteer as well.

**Comment by mattn** [comment]
Thanks all. I invited you to collaborators.
