### ISSUE TITLE
repo token shouldn't be required

### ISSUE THREAD

**Issue by maxlinc** [mattn/goveralls#18]
I was able to get goveralls working on travis, but I need to give it a repo_token for a public project.

The Coveralls documentation says repo_token is only needed for private projects:

> The option repo_token (found on your repository's page on Coveralls) is used to specify which project on Coveralls your project maps to. This is only needed for private repos and should be kept secret -- anyone could use it to submit coverage data on your repo's behalf.

**Comment by zippelmann** [comment]
Is it working with job_id and service_name ? I found something in the repository.

**Comment by mattn** [comment]
Yes, you can specify job_and service_name.

**Comment by lloydde** [comment]
> see: https://coveralls.io/docs/api
This is documented at https://coveralls.zendesk.com/hc/en-us/articles/201774865-API-Introduction

 Setting service_name to "travis-ci" and service_job_id to the Travis Job ID will automatically look up the appropriate build and repository, and assign the job correctly on Coveralls. -- <cite>[THE COVERALLS API][1]</cite>

[1]:https://coveralls.zendesk.com/hc/en-us/articles/201774865-API-Introduction

**Comment by lloydde** [comment]
This issue was fixed a month ago with 7fdbe144f03526a0df8b617d828ef667df27cfd4.
I recommend closing as fixed.
