### ISSUE TITLE
Discrepancy between gocov/go test -coverprofile and goveralls

### ISSUE THREAD

**Issue by nickpresta** [mattn/goveralls#19]
I'm trying to use Goveralls to report on my test coverage but I seem to be getting wildly different coverage values depending on which tool I run and how I run it.

I hope I'm doing something wrong or misunderstanding how to use goveralls and would appreciate some help. Thanks in advance.
## Using go test

```
go test -coverprofile=cover.out
# removed for brevity
PASS
coverage: 90.2% of statements
ok      github.com/NickPresta/gowave/wave   0.409s
```

90.2% coverage

I also have a `cover.out` file in the current directory that allows me to do `go tool cover -html=cover.out` and everything looks correct.
## Using gocov

```
gocov test | gocov report
# removed for brevity
github.com/NickPresta/gowave/wave        ---------------------------     90.20% (368/408)
```

90.2% coverage again. Awesome.
## Using goveralls

```
$ goveralls skal80cDbbobV3oSWMYAQpnf3Bwsa2WOy
ok      github.com/NickPresta/gowave/wave   0.407s
Job #9.1
https://coveralls.io/jobs/933643
```

goveralls (or Coveralls) seem to think that the coverage percentage is **93.76%** which makes no sense.
## Using goveralls with gocov JSON

```
$ gocov test > out.json
ok      github.com/NickPresta/gowave/wave   0.431s
$ goveralls -gocovdata=out.json skal80cDbbobV3oSWMYAQpnf3Bwsa2WOy
Job #11.1
https://coveralls.io/jobs/933646
```

This still reports that I have **93.76%** coverage, which is wrong, despite gocov still thinking it is 90.2%:

```
$ gocov report out.json
github.com/NickPresta/gowave/wave        ---------------------------     90.20% (368/408)
```
## Using goveralls with go test -coverprofile

```
$ goveralls -coverprofile=goveralls.out skal80cDbbobV3oSWMYAQpnf3Bwsa2WOy
Job #14.1
https://coveralls.io/jobs/933650
```

Goveralls (or Coveralls) seems to think here that I have **79.27%** coverage, which is even more strange.
## Extra Info

Goveralls version: `2bc52d4d83a9049cc72b50c46042b201e4da93ca`
Gocov version: `a683f3072f5f857b3cdbb7c19551824a24ca0403`
Go version: 1.2
My package: https://github.com/NickPresta/gowave

Also interesting is that the total number of lines seem to fluctuate on Coveralls between runs, which is also incorrect, depending on the source.

**Comment by jcelliott** [comment]
I'm seeing the same thing, about a 6% difference between the two on the latest version.

**Comment by mattn** [comment]
gocov return lines which contains start/end of the part. it's difficust to handle whether the line is passed or not.

**Comment by oryband** [comment]
:+1: any progress?

**Comment by devdazed** [comment]
is there any workaround for this?

**Comment by mattn** [comment]
At least goveralls doesn't use gocov. Could you please try in latest?

**Comment by mattn** [comment]
goveralls doesn't depend on gocov at least.
