### ISSUE TITLE
How can I support Gitlab CI?

### ISSUE THREAD

**Issue by agamm** [mattn/goveralls#191]
We need to support gitlab ci instead of circle ci.

**Comment by gdm85** [comment]
The environment variables are described here: https://docs.gitlab.com/ee/ci/variables/predefined_variables.html

I guess support could be easily added. @agamm have you searched on GitLab about projects already using `goveralls`?

**Comment by agamm** [comment]
Where are the changes supposed to be written? maybe I'll have time to PR. And is it only a map for the env vars?

**Comment by gdm85** [comment]
@agamm left some feedback on your PR; thanks!
