### ISSUE TITLE
Individual coverage badge and statistics for each sub-package

### ISSUE THREAD

**Issue by davecgh** [mattn/goveralls#36]
A common pattern is to design an application as a series of reusable and shareable sub-packages within the main repo where your application is essentially just a thin wrapper around these sub-packages.

For a similar example of the idea, consider how `golang.org/x/crypto/...`  works.  There are multiple packages housed under a single repository because they are all related to crypto, however they are intended to be independently used as needed.  For example, it's unlikely you would both use bcrypt and scrypt at the same time.

When you have sub-packages in this manner, it is ideal to report the individual test coverage of each package independently.  I know it is possible to merge the coverage of multiple packages into a single coverage report as discussed in #20 and, while that makes sense in certain scenarios, it does not make any sense in the scenario I've described.

Is it possible to massage goveralls/coveralls.io to provide individual coverage statistics and badges per sub-package?

**Comment by bkeroackdsc** [comment]
+1

**Comment by pierrebeaucamp** [comment]
+1

**Comment by mattn** [comment]
Should be fixed in https://github.com/mattn/goveralls/pull/74

If you still have an issue, please file new issue.
