### ISSUE TITLE
Couldn't find a repository matching this job.

### ISSUE THREAD

**Issue by sebest** [mattn/goveralls#39]
Hello,

I'm trying to use goveralls with travis pro (not the free version) but i always have this error message:
Bad response status from coveralls: 422 - {"message":"Couldn't find a repository matching this job.","error":true}

I checked that the repository exists in coveralls as i got the token from this place.

When i pass -service="" instead of the default value i have no errors but i don't see anything inside coveralls ui.

**Comment by sebest** [comment]
I think i fixed the issue using
-service=travis-pro

Maybe you should update the README for the travis pro example, as i think the default value is travis-ci , -service should not be required in the travis-ci.org (free) example?

**Comment by manan19** [comment]
I was facing the same issue.
+1 to the solution by @sebest
