### ISSUE TITLE
pass -tags to go test the same way as -race and -v are passed.

### ISSUE THREAD

**Issue by bolshoy** [mattn/goveralls#46]

**Comment by jonbonazza** [comment]
I would love this as well.

**Comment by mattn** [comment]
what situation do you expect?

```
$ gom test -tags
```
like this?

**Comment by jonbonazza** [comment]
In my particular case, I'd like to be able to run the following command:
```bash
$ gom test -v -cover -tags test
```

**Comment by mattn** [comment]
-branches flag help you?

**Comment by gonzaloserrano** [comment]
You removed the -branches flag AFAIK here https://github.com/mattn/goveralls/pull/88

I also need to pass flags, e.g `-tags integration`

**Comment by pladdy** [comment]
@mattn what if i i have sqlite dependency and my tests have to build with `-tags json1`
Is there a way to pass that to goveralls?
Like `goveralls -flags "-tags json1"`
