### ISSUE TITLE
Possible to use goveralls from a unsupported CI system?

### ISSUE THREAD

**Issue by paulcwarren** [mattn/goveralls#58]
Hi Mattn,

goveralls looks like exactly what we need.  It is a little unclear to me from the docs and also from my testing whether it is possible to use goveralls to push code coverage stats to coverall.io for a registered open source github repo using a CI system other than Travis or Drone, or one of the other known-about CI systems.

TIA
_Paul

**Comment by mattn** [comment]
It's possible to use any CI(s) if it can post via HTTP to coveralls.io .
See https://github.com/mattn/go-runewidth/blob/master/.travis.yml

**Comment by paulcwarren** [comment]
Thanks for the quick reply.  Just so i understand goveralls is tie to travis-ci?  But I can just POST directly to the coveralls.io REST api (assuming I form the right form-data json_file body).  does that sound about right?

**Comment by mattn** [comment]
yes, if you want to do it easily, goveralls will be useful.
