### ISSUE TITLE
Reports condition of an if as uncovered if only the block is uncovered.

### ISSUE THREAD

**Issue by eaburns** [mattn/goveralls#61]
A very common pattern is:
```
if err := doSomething(); err != nil {
  return err
}
```
If `return err` is uncovered, it also reports `if err := doSomething(); err != nil {` as uncovered even if that statement is in fact covered by a test. This over counts the number of uncovered statements by 1 for each if-return-err block.

**Comment by mattn** [comment]
https://coveralls.io/builds/2157295/source?filename=scan.go#L190

AFAICS, it seems passing.

**Comment by eaburns** [comment]
Maybe the difference is that there is no initialization statement in that if.

Here's what I'm seeing: https://coveralls.io/builds/5262466/source?filename=edit%2Fedit.go.
There are many if-statements that are clearly tested, just their condition is always false in the tests. The coverage report says that the if itself is never executed.

Compare to the coverage report of the same code here: https://gocover.io/github.com/eaburns/T/edit.

**Comment by mattn** [comment]
Maybe, gocov doesn't output the footprint which is passing there.

**Comment by eaburns** [comment]
I don't quite understand. Does than mean that the bug is upstream? Either way, thanks for looking. And thanks for this package.
