### ISSUE TITLE
cannot use test profile flag with multiple packages

### ISSUE THREAD

**Issue by vitalyisaev2** [mattn/goveralls#68]
Hello all.

I used ```goveralls``` to build coverage reports for my [repository](https://github.com/vitalyisaev2/skiena) in Travis-CI and Coveralls, and it worked good right up to the present day (even yesterday).

Unfortunately [the latest build](https://travis-ci.org/vitalyisaev2/skiena/jobs/116226137) failed with an error:
```bash
$ $HOME/gopath/bin/goveralls -service=travis-ci ./...
exit status 1: cannot use test profile flag with multiple packages
```

I assure that everything worked before it and there was no any major changes in the project structure. Thank you for considering my request.

**UPD**:
I've repaired my CI with the plenty of new tools (along with ```goveralls```). If anyone run into this issue too, have a look at my [.travis.yml](https://github.com/vitalyisaev2/skiena/blob/master/.travis.yml)

**Comment by smancke** [comment]
I have the same issue. 
When I omit the package argument (./...), like in the above workaround, the coverage of the sub packages is not reported. Any solutions?

**Comment by vitalyisaev2** [comment]
@smancke 

I've end up with this (if you don't mind using extra dependencies like ```ginkgo``` and ```gover```):

Create ```*.coverprofile``` files in every subpackage:
```bash 
ginkgo -r --randomizeAllSpecs -cover --failOnPending -coverpkg=./... --trace --race
```
Merge them into upperlevel ```gover.coverprofile```:
```bash
gover .
```
Post data to Coveralls:
```bash
goveralls -coverprofile=gover.coverprofile -service=travis-ci
```

**Comment by dotdoom** [comment]
This might have been broken by https://github.com/mattn/goveralls/commit/15b54ebcd27c366f762bd7c4793b6c5d7736d626

Looks like https://github.com/modocache/gover could be used as a workaround for now.

**Comment by willis7** [comment]
Same for me

**Comment by mattn** [comment]
Someone, could you please try `multiple-packages` branch?

**Comment by haya14busa** [comment]
I tried `multiple-packages` branch and it works great!

sample pull-request: https://github.com/haya14busa/go-vimlparser/pull/1

But I'm not sure it's ok to break backword compatibility and run test ./... by default.

**Comment by haya14busa** [comment]
I found `-coverpkg` option in `go test -h`

```
go test -v -coverprofile=coverage.out -coverpkg=./...
```

I didn't try this yet, but we might be able to use `goveralls -service=travis-ci -coverpkg=./...`

**Comment by haya14busa** [comment]
I tried `-coverpkg` option with this branch https://github.com/haya14busa/goveralls/tree/coverpkg and same sample pull-request and it works.

travis: https://travis-ci.org/haya14busa/go-vimlparser/jobs/158975881#L236
coverall: https://coveralls.io/jobs/18094927

`-coverpkg` option is added on Jun 28, 2013. https://github.com/golang/go/commit/97c19f0f721b1db634dcae6a766712533a8f1bd5

`-coverpkg` outputs result for no test file package and it's different from `go list ./...` and run `go test` for each package.

I think it's might be good to use `-coverpkg` option or introduce equivalent flag for `go list` instead of hardcoding `./...`.

**Comment by haya14busa** [comment]
I'm sorry, please ignore `-coverpkg` things.

`-coverpkg=./...` alone  doesn't run test all pakcages and
`go test -v -coverprofile=coverage.out -coverpkg=./... ./...`
doesn't work... (`cannot use test profile flag with multiple packages`)

I guess `go test` should allow `./...` arg with `-coverprofile` when  `-coverpkg` is given, but I may miss something...

**Comment by haya14busa** [comment]
FYI: I found the issue for -coverprofile with multiple packages https://github.com/golang/go/issues/6909#issuecomment-123922352

Anyway,  +1 for `multiple-packages` branch.

golist & run go test for each packages doesn't support running one-e2e test and get coverage from multiple dependent sub packages https://github.com/golang/go/issues/6909#issuecomment-208087927
But, I guess it's not a big problem.

**Comment by mattn** [comment]
closed by https://github.com/mattn/goveralls/pull/74
