### ISSUE TITLE
GOARCH=386 compability problem

### ISSUE THREAD

**Issue by MichaelMonashev** [mattn/goveralls#71]
More information: https://travis-ci.org/MichaelMonashev/sync/jobs/148512802 and https://travis-ci.org/MichaelMonashev/sync/builds/148512800 .

**Comment by mattn** [comment]
What do you mean bug? If goveralls works with unexpected behavior, it may be a bug. But as far as I can see the travis logs, goveralls doesn't start. Maybe, it seems that your .travis.yml is wrong.

**Comment by MichaelMonashev** [comment]
This travis config https://github.com/MichaelMonashev/sync/blob/7010eb45af49789410aed2e71214336b6e726e3f/.travis.yml corresponding with https://travis-ci.org/MichaelMonashev/sync/jobs/148512802 .

I run goveralls in very simple way:
- if [[ "$GOARCH" == "amd64" ]]; then go test -v -race -covermode=count -coverprofile=profile.cov ./netmutex; else go test -v -covermode=count -coverprofile=profile.cov ./netmutex; fi
- $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci

**Comment by MichaelMonashev** [comment]
May be some lib that is required by the goveralls is not found.

**Comment by mattn** [comment]
If installation of goveralls are failed, this line sholud failed.

https://travis-ci.org/MichaelMonashev/sync/jobs/148512802#L160

**Comment by MichaelMonashev** [comment]
@mattn , you were right.

Do you know right path to goveralls?
$HOME/gopath/bin/goveralls and goveralls don`t work in all cases. See my new try: https://travis-ci.org/MichaelMonashev/sync/builds/148523896

**Comment by MichaelMonashev** [comment]
$GOPATH/bin/goveralls don't work too :-(

**Comment by mattn** [comment]
You can see bin directory with `go env` maybe.

**Comment by MichaelMonashev** [comment]
this line fix my problem

export PATH=$PATH:$GOPATH/bin/:$GOPATH/bin/linux_386/:$GOPATH/bin/darwin_386/

Thank you for help.

**Comment by mattn** [comment]
okay. closing.
