### ISSUE TITLE
How to supress this error "Post https://coveralls.io/api/v1/jobs: net/http: TLS handshake timeout"

### ISSUE THREAD

**Issue by MichaelMonashev** [mattn/goveralls#72]
https://travis-ci.org/MichaelMonashev/sync/jobs/148532887

I think this error rise here: https://github.com/mattn/goveralls/blob/master/goveralls.go#L226 and "shallow" flag don`t hide it.

**Comment by mattn** [comment]
goveralls will not suppress this error because i think this is not a bug of goveralls. so you need to write script that suppress this error. and specify it on .travis.yml .
