### ISSUE TITLE
[question] How can I pass specific araguments which belong to test

### ISSUE THREAD

**Issue by hiromaily** [mattn/goveralls#73]
Hi, I wonder how to pass specific arguments to my test.
When test is run, it's passed arguments like ```go test -v -a xxx -b yyy -c zzz```

You may recommend using profile like goveralls -coverprofile=coverage.out.
When running goveralls after getting coverage.out by go test, error was shown.
```
gocover.go:42: Can't find can't find "main.go": cannot find package "command-line-arguments/" in any of:
	/usr/local/Cellar/go/1.7/libexec/src/command-line-arguments (from $GOROOT)
```

Thanks.

**Comment by kiliankoe** [comment]
I'm also interested in this. I'm using [dvr](https://github.com/orchestrate-io/dvr) to record tests accessing online resources and would need to run `go test -dvr.Replay .`. I'd love to know how to make this work together with goveralls, thanks 😊

**Comment by hiromaily** [comment]
I forgot to feedback.
I've solved it.

First, run test respectively.
In my case, main package is not located on root directory. it's here ./cmd/xxxxx/main.go.
That's why I changed directory for execution of ```go test``` and ```Goveralls command```.

As an example, my command is the below.
```
  - cd ${MAIN_PATH};go test -v -covermode=count -coverprofile=profile.cov -f ../../configs/travis.toml -om 0
```
I run test and got coverprofile.
Next run Goveralls with setting -coverprofile as below.
```
  - cd ${MAIN_PATH};goveralls -coverprofile=profile.cov -service=travis-ci
```

I could run without problems.

Thanks.

**Comment by mattn** [comment]
Closable?

**Comment by hiromaily** [comment]
Yes, thanks!

**Comment by kiliankoe** [comment]
Awesome, thanks for the hint! 

Just a quick question, what is the purpose of -f, -o and -m in the first command? I can't see the documented for `go test` and am curious.

**Comment by hiromaily** [comment]
@kiliankoe 
I'm sorry to confuse you.
I must've written more understandable.

It's just dependent on my test.
My test needs these araguments. (-f ../../configs/travis.toml -om 0).
That's it.

**Comment by kiliankoe** [comment]
Oh ok gotcha, thanks so much for the reply! :)
