### ISSUE TITLE
No way to pass arguments to go test

### ISSUE THREAD

**Issue by mvdan** [mattn/goveralls#78]
I want to do `go test -short`, not `go test`. Instead of some flags being passed on, like `-covermode` and `-v`, flags starting with `test.` should be passed on to the test program. This is what test binaries do as well.

Then you could use `-test.short`, `-test.v` and such.

**Comment by nikkolasg** [comment]
I'm also very interested in any way to pass a arguments to `go test` such as `-race` as it does not seem to be the standard flags.
