### ISSUE TITLE
Should gitinfo use CI_BRANCH/TRAVIS_BRANCH/CIRCLE_BRANCH instead of GIT_BRANCH?

### ISSUE THREAD

**Issue by fsouza** [mattn/goveralls#79]
We're running goveralls in a private drone service, and there's no GIT_BRANCH environment variable, there's only CI_BRANCH (see http://readme.drone.io/usage/variables/).

Using rev-parse doesn't work either because drone checks out the specific commit (CI_COMMIT) before running the tests. Should goveralls look for CI_BRANCH as well? I know that this can open the gate to hell (travis has TRAVIS_BRANCH and circle has CIRCLE_BRANCH), but this is something other coveralls library support:

- https://pypi.python.org/pypi/coveralls
- https://coveralls.zendesk.com/hc/en-us/articles/201347419-Coveralls-currently-supports

If that's acceptable, I can send a PR :)

**Comment by mattn** [comment]
Could you please send me pull-request?

**Comment by fsouza** [comment]
Sure, I'll do it tomorrow, unless I can't recover from elections result.
