### ISSUE TITLE
Unexpected inclusion of subdirectory

### ISSUE THREAD

**Issue by blang** [mattn/goveralls#82]
The coverage of [blang/semver](https://github.com/blang/semver) dropped between two builds because the last build suddenly included a separate subdirectory (examples).

Is that a new semantic of goveralls?

Relevant:
[Coveralls Status Page](https://coveralls.io/github/blang/semver)
[Build that suddenly included subdirectory # 31](https://coveralls.io/builds/8982261)
[Previous build, directory not included # 30](https://coveralls.io/builds/6830171)

Drone.io build settings:
```
go get
go build
go get github.com/axw/gocov/gocov
go get github.com/mattn/goveralls
goveralls -service drone.io -repotoken $COVERALLS_TOKEN
cd examples
go build
```

**Comment by mattn** [comment]
Coverage result doesn't depend on the changes of the commit as far as implementation of goveralls. Strange.

**Comment by blang** [comment]
Does goveralls by default include all subdirectories?
Since it uses `go list ./...`, it might include subdirectories/packages, if i read it correctly.

https://github.com/mattn/goveralls/commit/de5a843d32a9dacf3f70f364b1af28dc213f5f3e#diff-1973b7a49e2b44eaf95ef6a88c0d8d2bR80

**Comment by blang** [comment]
Ok fixed it by adding the `-package "github.com/blang/semver"` flag to exclude the subdirectory since without the `-package` flag it uses `go list ./...`.
