### ISSUE TITLE
Adding branch coverage support

### ISSUE THREAD

**Issue by nickmerwin** [mattn/goveralls#87]
Hi @mattn, we're rolling out branch coverage support for Coveralls.io and have landed it in two other integration libraries:

Node: https://github.com/nickmerwin/node-coveralls/commit/d571dac62547f487b3862aca8bf367e95957d904

Python: https://github.com/coveralls-clients/coveralls-python/pull/145

There are more details about the new `branches` parameter here:
https://coveralls.zendesk.com/hc/en-us/articles/201350799-API-Reference

I wanted to get it on your radar now in case you or another maintainer has spare time to add this support to goveralls.

Thank you!

**Comment by nickmerwin** [comment]
:zap: amazing, thank you @mattn!

**Comment by myint** [comment]
#88 looks like Git branches rather than [conditional branches](https://nedbatchelder.com/files/sample_coverage_html/cogapp_whiteutils_py.html) that @nickmerwin was talking about.

**Comment by nickmerwin** [comment]
@mattn looking back at this I believe @myint is correct -- I may have incorrectly assumed Golang supports conditional branch coverage; I did a page-search for it here https://blog.golang.org/cover and there were a few hits, but looking back it's less than clear.

@mattn could you shed some light?

**Comment by mattn** [comment]
Ah, sorry my bad. I'll revert #88

**Comment by aermakov-zalando** [comment]
Could you reopen the issue? Branch coverage is still missing for Go projects.

**Comment by mattn** [comment]
I wonder branch coverage is supported on coveralls.

**Comment by gdm85** [comment]
Go has no native branch coverage; see [this SO answer for more details](https://stackoverflow.com/a/53396774).

Since [upstream Go has turned down the feature](https://github.com/golang/go/issues/28888) I suggest to **not** support it in goveralls and close this issue as `won't fix`; @mattn thoughts?
