### ISSUE TITLE
Crashes with bogus "flag redefined" panic

### ISSUE THREAD

**Issue by mvdan** [mattn/goveralls#89]
Steps to reproduce:

* Fetch `mvdan/sh` at this commit: https://github.com/mvdan/sh/commit/24105a888955c3a3c655107ccf4b79b84e4a0357
* Run `goveralls` (latest version) inside the root of the repo

```
exit status 1: warning: no packages being tested depend on github.com/mvdan/sh/cmd/gosh
warning: no packages being tested depend on github.com/mvdan/sh/interp
/tmp/go-build510370213/github.com/mvdan/sh/cmd/shfmt/_test/shfmt.test flag redefined: p
panic: /tmp/go-build510370213/github.com/mvdan/sh/cmd/shfmt/_test/shfmt.test flag redefined: p

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc4200480c0, 0x623ae0, 0xc4200127aa, 0x56c48d, 0x1, 0x5738ad, 0x26)
        /home/mvdan/tip/src/flag/flag.go:793 +0x415
flag.(*FlagSet).BoolVar(0xc4200480c0, 0xc4200127aa, 0x56c48d, 0x1, 0xc420035e00, 0x5738ad, 0x26)
        /home/mvdan/tip/src/flag/flag.go:566 +0x70
flag.(*FlagSet).Bool(0xc4200480c0, 0x56c48d, 0x1, 0x623400, 0x5738ad, 0x26, 0x51b7fc)
        /home/mvdan/tip/src/flag/flag.go:579 +0x7f
flag.Bool(0x56c48d, 0x1, 0xc42000a300, 0x5738ad, 0x26, 0xc42000a3a0)
        /home/mvdan/tip/src/flag/flag.go:586 +0x5e
github.com/mvdan/sh/cmd/gosh.init()
        github.com/mvdan/sh/cmd/gosh/_obj/main.go:16 +0x92
main.init()
        <autogenerated>:1 +0x5f
FAIL    github.com/mvdan/sh/cmd/shfmt   0.003s
```

Happens on Travis too: https://travis-ci.org/mvdan/sh/jobs/220619066

**Comment by mvdan** [comment]
For reference, a temporary workaround: https://github.com/mvdan/sh/commit/5d2768cca4a02c1750fe3cbaf4d69a455814873d

**Comment by mattn** [comment]
it's not issue of goveralls?

**Comment by mvdan** [comment]
How so? I can't reproduce the issue without goveralls, and the code was certainly correct.

**Comment by mattn** [comment]
goveralls run tests for all packages in your repository. And your repository include two apps in cmd directory. Then, `"p"` is redefined.

Please try to separate tests.

```
go test -coverprofile cover-shfmt.out github.com/mvdan/sh/cmd/shfmt
go test -coverprofile cover-fileutil.out github.com/mvdan/sh/fileutil
go test -coverprofile cover-interp.out github.com/mvdan/sh/interp
go test -coverprofile cover-syntax.out github.com/mvdan/sh/syntax

goveralls -coverprofile cover-shfmt.out,cover-fileutil.out,cover-interp.out,cover-syntax.out
```

**Comment by mvdan** [comment]
> goveralls run tests for all packages in your repository.

This works just fine, i.e. `go test ./...` succeeds.

> And your repository include two apps in cmd directory. Then, "p" is redefined.

The flag "p" is defined in two separate main packages. Why is that an issue?

I still can't reproduce the issue with plain `go` commands and can't get `goveralls` to print exactly what it's executing - tried `-debug` and `-v`.

**Comment by mattn** [comment]
goveralls should merge coverage of separated result of tests. so internally, goveralls runs following.

```
go test -coverpkg=github.com/mvdan/sh/cmd/gosh,github.com/mvdan/sh/cmd/shfmt,github.com/mvdan/sh/fileutil,github.com/mvdan/sh/interp,github.com/mvdan/sh/syntax github.com/mvdan/sh/cmd/gosh
go test -coverpkg=github.com/mvdan/sh/cmd/gosh,github.com/mvdan/sh/cmd/shfmt,github.com/mvdan/sh/fileutil,github.com/mvdan/sh/interp,github.com/mvdan/sh/syntax github.com/mvdan/sh/cmd/shfmt
go test -coverpkg=github.com/mvdan/sh/cmd/gosh,github.com/mvdan/sh/cmd/shfmt,github.com/mvdan/sh/fileutil,github.com/mvdan/sh/interp,github.com/mvdan/sh/syntax github.com/mvdan/sh/fileutil
go test -coverpkg=github.com/mvdan/sh/cmd/gosh,github.com/mvdan/sh/cmd/shfmt,github.com/mvdan/sh/fileutil,github.com/mvdan/sh/interp,github.com/mvdan/sh/syntax github.com/mvdan/sh/interp
go test -coverpkg=github.com/mvdan/sh/cmd/gosh,github.com/mvdan/sh/cmd/shfmt,github.com/mvdan/sh/fileutil,github.com/mvdan/sh/interp,github.com/mvdan/sh/syntax github.com/mvdan/sh/syntax
```

And coverpkg is generated from `go list ./...` so it contains cmd/gosh.

**Comment by mvdan** [comment]
Okay, I get the crash now. Thanks.

This still seems like a goveralls bug to me. If the repo being tested happens to have multiple executables that share flag names, it won't work. You proposed a manual workaround - can't goveralls do that automatically instead?

**Comment by mvdan** [comment]
Friendly bump - would still like to be able to use goveralls without having to resort to manual commands like that. Happy to try out possible solutions.

**Comment by gdm85** [comment]
@mvdan in this case perhaps it is better to generate the coverage profile file with `go test ...` and then pass it over to `goveralls`?
