### ISSUE TITLE
gocover.go:58: Profile FileName is different

### ISSUE THREAD

**Issue by littledot** [mattn/goveralls#93]
I'm trying to integrate coveralls for my project https://github.com/littledot/mockhiato/pull/10 However, I am getting the following error on Travis. 

```
$ $HOME/gopath/bin/goveralls -service=travis-ci
08:33:53 gocover.go:58: Profile FileName is different
```
This is reproducible locally as well. Do you know what causes this error?

**Comment by mattn** [comment]
@haya14busa Sorry, I don't understand this part well.

https://github.com/mattn/goveralls/blob/42c8a693f7f0977d9e17901324a9dd149a0f71f6/gocover.go#L58

Could you please explain what this mean?

**Comment by maxibanki** [comment]
Hi,
I have the same issue now, I haven't changed anything related to the `go test` or `goveralls` command. Very strange, it has worked all the time before.

Do you have any updates related to this issue?

**Comment by kyessenov** [comment]
Hit this issue in another project. Any workaround?

**Comment by mattn** [comment]
What repo?

**Comment by kyessenov** [comment]
https://github.com/google/go-jsonnet/pull/152

**Comment by mattn** [comment]
now problem was fixed. could you please try in latest update?

**Comment by kyessenov** [comment]
Yay, it passed the build now!

**Comment by mattn** [comment]
If you still have this issue, please reopen this. Thanks.

**Comment by maxibanki** [comment]
Thanks for the update, but now I'm having a different issue and I don't know why:
https://travis-ci.org/maxibanki/golang-url-shortener/builds/301796940
Would be cool if you can take a look at it :)
