### ISSUE TITLE
The ignore feature is very picky about the path

### ISSUE THREAD

**Issue by rmohr** [mattn/goveralls#95]
Hi @mattn,

A very nice little tool.

I am using the `-ignore` flag to exclude all my gomock generated code from code coverage. When I run

```
goveralls -package=./pkg/... -ignore=$(find -name generated_mock*.go -printf "%P\n" | paste -d, -s)
```
it does ignore my files.

When I run 

```
goveralls -package=./pkg/... -ignore=$(find -name generated_mock*.go | paste -d, -s)
```

it does not.

The difference is, that in the first example, I am removing the leading `./` from my `find` results. In the second example, I don't.

So passing in `./pkg/generated_mock.go` would fail, whereas `pkg/generated_mock.go` would not.

**Comment by mattn** [comment]
-ignore options is patttern. So you can use `pkg/*_mock.go`.

**Comment by rmohr** [comment]
Missed that. Thanks. :+1:
