### ISSUE TITLE
Question - goveralls parallel

### ISSUE THREAD

**Issue by mch1307** [mattn/goveralls#97]
Hi,
I need to run my tests with no parallel. I usually do this with 
`go test ./... -p 1`
But I did not find a way to pass this option to goveralls. Tried with env var GOMAXPROCS, COVERALLS_PARALLEL but no success. Is this possible?
Thanks

**Comment by gdm85** [comment]
See `goveralls -h`:
```
  -flags value
    	extra flags to the tests
```

You want to use something like: `goveralls -flags '-count=1'`.
